### ISSUE TITLE
调用tts时会结束主线程

### ISSUE THREAD

**Issue by Snychng** [SynopAI/ChatMate-proto#1]
https://github.com/SynopAI/ChatMate-proto/blob/5b7b7cf09defa63368a844ad48b69aa40c43b9e6/main.py#L186-L190

**Comment by Snychng** [comment]
好像是play_audio的问题

**Comment by Mrered** [comment]
我计划用Go重构，完了我测试一下

**Comment by Mrered** [comment]
据说已经解决了？
